print("'print' is a function name.\nFunctions are able to cause some effect and evaluate a value(s), among others.\nFunctions can come from Python itself, installed modules or written yourself.\nFunction names should be self evident, like how 'print' is.\n")
print("All functions can take arguments. For example, 'print' is taking strings as arguments right now.\nFunctions can take as many arguments as needed, including zero.\nAll functions must have parentheses after them '()' to signify them as functions.\n")
print("All strings must be inside quotes(\"\" or '')\nStrings are literals and stored as data.\n")
print("A function with parentheses and argument(s) forms function invocation.\nWhen invoked, Python checks the name is legal (doesn’t conflict with existing names), that there are enough arguments to meet the function’s requirements, then jumps to the code defining the function and runs said code, returning to the original position in code when done.\n")
print("The 'print' function takes an argument, converts it into human-readable form and sends it to the output device, appearing on your screen. That is it's effect.\nPrint can take virtually all types of data as arguments.\nPrint has no evaluation – only effect.\n")
print("Python can accept empty lines, but cannot handle more than one instruction per line.\nOne instruction can span multiple lines though.\n")
print("Each invocation of print() appears on separate lines.\nEach invocation can contain different arguments (in this case, strings) and are executed in the same order they appear in code.\n")
print("Print() with no arguments outputs a newline.\n")
print("Backslash(\) is an escape character that tells the program that the following character has a different meaning.\nn following a \ invokes a newline the same that print() does.\nUsing \ before another \ will allow it to appear in code.\n")
print("You can have multiple arguments in the same function by separating them with a comma (,).\n")
print("Print() puts a space between all outputted arguments by default.\n")
print("Print() arguments are positional and are executed in order.\nKeyword arguments can be used to change a function’s behaviour.\n")
print("The keyword argument (end=” ”) consists of the keyword (end), an equal sign (=) and a value (“ “).",end=" ")
print("All keyword arguments have to be put after the last positional argument.",end="\n")
print("Sep", "(separator)", "is", "another", "keyword", "argument", "that", "defines", "how", "separations", "(i.e.", "spaces)", "are", "handled.\n",sep="_")
print("You", "can", "use", "more", "than", "one", "keyword", "argument", "per", "line",sep=" ",end=".")
print("\nLiterals are data that is the data itself and nothing else. For example, 123 is the number one-hundred and twenty three and nothing else, whereas c could be anything. 123 is a literal, c is not.\n")
print("2",2,"The former 2 is a string, whereas the latter is an integer, yet both are still literals.\nStrings are stored in memory as letters and numbers, but integers are stored as bits.")
num_str = "2"
num_int = 2
print(num_str, num_int,"\n")
print("There are two ways of storing numerical data: integers are whole numbers and floats (floating point) are not and have decimal places (e.g. 3.16).\nThe different types of data are stored differently in data and cannot be used together without additional work.\nIntegers can only be stored as digits and nothing else, only with the exception of underscores. (e.g. 1111111 & 1_111_111 are okay, 1,111,111 &  1 111 111 are not.)")
int1 = 1_111_111
int2 = 1111111
print(int1, int2,"\n")
print("You can put a minus in front of numbers to make them into negative ones.")
int3 = -1111111
print(int3,"\n")
print("Likewise, you can use a plus in front of numbers to define them as positive, but that is unnecessary as numbers are positive by default.")
int4 = +1111111
int5 = 1111111
print(int4, int5, "\n")
print("You can represent Octal values by using the 0o prefix.")
oct1 = 0o123
print(oct1, "\n")
print("Likewise, you can use 0x to represent hexadecimal values.")
hex1 = 0x123
print(hex1, "\n")
print("Numbers that have a decimal point (e.g. 2.5) are stored as floats.")
float1 = 2.5
print(float1, "\n")
print("Leading zeroes can be omitted from floats.")
float2 = .4
print(float2, "\n")
print(4,",", 4.0, "- It’s the point that makes a float.\n")
print("The letter ‘e’ can be used to make floats and stands for exponent. e is used as ‘ten to the power of’ and as such 3e8 means 3x10^8.")
exp1 = 3E8
print(exp1)
print("The exponent (the value after the E) has to be an integer. The base (the value in front of the E) may be an integer.")
exp2 = 3.2E8
print(exp2, "\n")
print("You can use negative values as your powers.")
exp3 = 6.62607E-34
print(exp3)
print("Python chooses the more economical way to display a number’s representation, as shown above.\n")
print("Strings are used to process text and needs to be inside quotes.\n")
print("You can use both “” and ‘’ to quote strings in order to get around the required use of said characters within strings. For example, you can use “” to quote the word I’m, or use ‘’ to quote a spoken quote. ")
print("I'm", '"the one who knocks."\n')
print("Booleans are also literals and are represented as True for 1 and False for 0; both must begin with a capital.\n")
print("Print() can also be used for operations and expressions, such as mathematical equations.")
print(2+2, "\n")
print("Operators are symbols that are able to operate on values, like +-/* but can be more than the typical mathematical ones you’re used to.\n")
print("** is the exponentiation (power) operator and applies the exponent on the right to the base on the left.")
int6 = 2 #float(input("Please enter a number as your base argument: "))
int7 = 3 #float(input("Please enter a number as your operational argument: "))
print("The answer to your exponentiational equation is: ",int6, "**", int7, "=", int6 ** int7, "\n")
print("* is the multiplication operator.",int6, "*", int7, "=", int6 * int7, "\n")
print("/ is the divisional operator and applies to the divisor on the right to the dividend on the left.",int6, "/", int7, "=", int6 / int7, "Division will always result in a float.","\n")
print("// is the integer divisional operator and will always round the result to the lesser integer.", int6, "//", int7, "=", int6 // int7, "\n")
print("Negative values can be used in division.\n")
print("% is the remainder or modulo operator which returns the reminder after division.", int6, "%", int7, "=", int6 % int7,"\n")
print("Any form of division doesn’t work.\n")
print("+ is the addition operator.", int6, "+", int7, "=", int6 + int7,"\n")
print("- is the subtraction operator in its binary form, but can be used to signify a negative value in its unary form.", int6, "-", int7, "=", int6 - int7,"\nThe left argument in subtraction is the minuend and the right the subtrahend.\n+ is also unary when signifying a positive number, although is rather redundant as numbers are positive by default.\n")
int8 = 4 #float(input("Please enter a number as your third argument: "))
print("Multiplications precede additons.\nOperators have a hierarchy of priorities that determines their order of execution.", int6, "+", int7, "*", int8, "=", int6 + int7 * int8,"\n")
print("Some operators have equal priority and as such then rely on their sided binding to determine order of execution. If it is left-sided then it will run from left to right, and right-sided will run from right to left.",int6, "%", int7, "%", int8, "=", int6 % int7 % int8,"\n")
print("%, the remainder or modulo operator has left-sided binding.\n")
print("**, the exponentiation operator has right-sided binding.",int6, "**", int7, "**", int8, "=", int6 ** int7 ** int8,"\n")
print(""" Current known hierarchy of priorities.
+ -   | unary
**    |
* / % |
+ -   | binary\n""")
print("Subexpressions in parentheses are always calculated first and can be used to change the natural order of a calculation.\n")
print("Names must only contain upper and lower-case letters, digits and underscores.\nThey must begin with a letter or an underscore (as they are classed as letters).\nNames are case sensitive and cannot be one of Python’s reserved keywords.\n")
print("and | as | assert\nbreak\nclass | continue\ndef | del\nelif | else | except | exec\nfinally | for | from\nglobal\nif | import | in | is\nlambda\nnot\nor\npass | print\nraise | return\ntry\nwhile | with\nyield\nDon’t use these words in their exact context as names. They are the reserved keywords.\n")
print("Variable can contain anything and have values assigned to them using the assignment operator (=).\n")
print("You can reassign values to variables as many times as needed by using the assignment operator.\n")
print("You can put comments in your code to describe whats going on by using the hash symbol #.\nCreated names should be self-commenting.\n")
print("You can omit using the same variable name twice if you are reassigning a value to it by doing (variable (operator)=(new value)).\n")
print("The input() function reads data entered by the user and returns the same data to the running program as a string.\n")
print("Input() can also print a statement to the screen before accepting input by putting a desired string into the parentheses.\n")
print("You cant use data returned from input() in any arithmetic operation.\n")
print("You can use int(input()) and float(input()) to convert accepted data into integers and floats respectively.\n")
print("It may not always be necessary to use a variable to store a result if it is only going to be used/displayed once. In such cases, the desired operations can be done within the print command to return the output.\n")
print("+ is also used as a concatenation operator when used" + "with two strings to ‘glue’ them together in a left-sided bind.\n")
print("* Is also used as a replication operator when used with a string and a number – resulting in said string being repeated the number of times specified.\n")
print("Numbers can be converted into strings using the str() argument.\n")
print("You can convert an entire arithmetic equation into a string to remove the need for commas.\n")
